--- #YAML:1.0
name:               Text-Conversation
version:            0.050
abstract:           Turn a conversation into threads, one line at a time.
author:
    - Rocco Caputo <rcaputo@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Lingua::Stem::Snowball:  0.7
    Lingua::StopWords::EN:  0
    String::Approx:       3.23
resources:
    license:     http://dev.perl.org/licenses/
    repository:  http://github.com/rcaputo/text-conversation
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
