---
abstract: 'Turn a conversation into threads, one line at a time.'
author:
  - 'Rocco Caputo <rcaputo@cpan.org>'
build_requires:
  Carp: 1.26
  Scalar::Util: 1.29
  Test::More: 0.98
  lib: 0
  perl: 5.004
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-Conversation
requires:
  Lingua::Stem::Snowball: 0.952
  Lingua::StopWords::EN: 0.08
  String::Approx: 3.27
  constant: 0
  strict: 0
  vars: 0
  warnings: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Text-Conversation
  homepage: http://search.cpan.org/dist/Text-Conversation/
  license: http://dev.perl.org/licenses/
  repository: git://github.com/rcaputo/text-conversation.git
version: 0.053
