# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Text-Conversation
version:      0.03
version_from: lib/Text/Conversation.pm
installdirs:  site
requires:
    Lingua::Stem::Snowball:        0.7
    Lingua::StopWords::EN:         0
    String::Approx:                3.23

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
